version: "3"

services:
  project:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      SERVER_PORT: 3000
      DB_HOST: bzgitdevsar0s5hytyfy-postgresql.services.clever-cloud.com
      DB_PORT: 50013
      DB_NAME: bzgitdevsar0s5hytyfy
      DB_USERNAME: unnlg28a7vdebimwpfgh
      DB_PASSWORD: r8ufaYqDp8qxLcnpWzHpjz05j6ZRCu
      JWT_SECRET_KEY: very-secret-key